filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/*.log

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: elastic
  password: changeme%

setup.kibana:
  host: "kibana:5601"